article/urls.py
# 引入path
from django.urls import path

# 正在部署的应用的名称
app_name = 'article'
from . import views

urlpatterns = [
    
    path('', views.IndexView.as_view(), name='index'),
    # path函数将url映射到视图
    path('article-list/', views.article_list, name='article_list'),
    # 文章详情
    path('article-detail/<int:id>/', views.article_detail, name='article_detail'),
    #path('article-detail2/<int:id>/',views)
    # 写文章
    path('article-create/', views.article_create, name='article_create'),
    # 删除文章
    path('article-delete/<int:id>/', views.article_delete, name='article_delete'),
    # 修改文章
    path('article-update/<int:id>/', views.article_update, name='article_update'),
]

django_blog/urls.py
from django.contrib import admin
# 记得引入include
from django.urls import path, include
from django.views.generic import TemplateView
# 存放映射关系的列表
urlpatterns = [
    path('',TemplateView.as_view(template_name='base.html')),
    path('admin/', admin.site.urls),

    # 新增代码，配置app的url
    path('article/', include('article.urls', namespace='article')),
    # 用户管理
    path('userprofile/', include('userprofile.urls', namespace='userprofile')),
    path('password-reset/', include('password_reset.urls')),
]

article/models.py
from django.db import models
# 导入内建的AbstractUser模型。
from django.contrib.auth.models import AbstractUser
# timezone 用于处理时间相关事务。
from django.utils import timezone


class User(AbstractUser):
    '''
    用户定义
    '''
    class Meta(AbstractUser.Meta):
        verbose_name = '用户'
        verbose_name_plural = '用户'


class ArticlePost(models.Model):
    '''
    博客文章数据模型
    '''
    # 文章作者。参数 on_delete 用于指定数据删除的方式
    author = models.ForeignKey(User, on_delete=models.CASCADE)

    # 文章标题。models.CharField 为字符串字段，用于保存较短的字符串，比如标题
    title = models.CharField(max_length=100)

    # 文章正文。保存大量文本使用 TextField
    body = models.TextField()
    # 文章浏览量  PositiveIntegerField是用于存储正整数的字段
    views_counts = models.PositiveIntegerField(default=0)
    # 文章创建时间。参数 default=timezone.now 指定其在创建数据时将默认写入当前的时间
    created = models.DateTimeField(default=timezone.now)

    # 文章更新时间。参数 auto_now=True 指定每次数据更新时自动写入当前时间
    updated = models.DateTimeField(auto_now=True)

    # 内部类 class Meta 用于给 model 定义元数据

    class Meta:
        # ordering 指定模型返回的数据的排列顺序
        # '-created' 表明数据应该以倒序排列
        ordering = ('-views_counts',)
        verbose_name = '文章'
        verbose_name_plural = verbose_name

    # 函数 __str__ 定义当调用对象的 str() 方法时的返回值内容
    def __str__(self):
        # return self.title 将文章标题返回
        return self.title

article/forms.py
# 引入表单类
from django import forms
# 引入文章模型
from article.models import ArticlePost
from mdeditor.fields import MDTextFormField


class ArticlePostForm(forms.ModelForm):
    '''
    表单  
        标题
        内容
    '''
    title = forms.CharField()
    body = MDTextFormField()

    class Meta:
        # 指明数据模型来源
        model = ArticlePost
        # 定义表单包含的字段
        fields = ('title', 'body')

article/views.py
# 引入redirect重定向模块
from django.core.paginator import Paginator
# 导入 HttpResponse 模块
from django.http import HttpResponse
from django.shortcuts import redirect, render
# 类视图
from django.views.generic import ListView

import markdown
from article.forms import ArticlePostForm

from .models import ArticlePost, User

# 引入 Q 对象
from django.db.models import Q

# 引入验证登录的装饰器
from django.contrib.auth.decorators import login_required


class IndexView(ListView):
    '''
    首页展示
    '''

    template_name = 'index.html'
    context_object_name = 'article_list'
    model = ArticlePost

    # def get_context_data(self, **kwargs):
    #     kwargs['category_list'] = ArticlePost.objects.all().order_by('name')
    #     return super(IndexView, self).get_context_data(**kwargs)


class Author(ListView):
    '''
    获取作者信息
    '''
    pass


def article_list(request):
    '''
    博客文章列表
    '''

    # 根据GET请求中查询条件
    # 返回不同排序的对象数组
    search = request.GET.get('search')
    order = request.GET.get('order')
    # 用户搜索逻辑
    if search:
        if order == 'views_counts':
            # 用 Q对象 进行联合搜索
            article_list = ArticlePost.objects.filter(
                Q(title__icontains=search) |
                Q(body__icontains=search)
            ).order_by('-views_counts')
        else:
            article_list = ArticlePost.objects.filter(
                Q(title__icontains=search) |
                Q(body__icontains=search)
            )
    else:
        # 将 search 参数重置为空
        search = ''
        if order == 'total_views':
            article_list = ArticlePost.objects.all().order_by('-total_views')
        else:
            article_list = ArticlePost.objects.all()

    # 每页显示 5 篇文章
    paginator = Paginator(article_list, 5)
    # 获取 url 中的页码
    page = request.GET.get('page')
    # 将导航对象相应的页码内容返回给 articles
    articles = paginator.get_page(page)

    # 需要传递给模板（templates）的对象
    context = {'articles': articles}

    # render函数：载入模板，并返回context对象
    return render(request, 'article/article_list.html', context)


def article_detail(request, id):
    '''
    文章详情页
    '''
    # 取出相应的文章
    article = ArticlePost.objects.get(id=id)

    # 浏览量 +1
    article.views_counts += 1
    article.save(update_fields=['views_counts'])

    # 将markdown语法渲染成html样式
    md = markdown.Markdown(
        extensions=[
            # 包含 缩写、表格等常用扩展
            'markdown.extensions.extra',
            # 语法高亮扩展
            'markdown.extensions.codehilite',
            # TOC,目录显示
            'markdown.extensions.toc',
        ])
    article.body = md.convert(article.body)

    # 需要传递给模板的对象
    context = {'article': article, 'toc': md.toc }
    # 载入模板，并返回context对象
    return render(request, 'article/article_detail.html', context)


@login_required(login_url='/userprofile/login/')
def article_create(request):
    '''
    写文章的视图
    '''
    # 判断用户是否提交数据
    if request.method == "POST":
        # 将提交的数据赋值到表单实例中
        article_post_form = ArticlePostForm(data=request.POST)
        # 判断提交的数据是否满足模型的要求
        if article_post_form.is_valid():
            # 保存数据，但暂时不提交到数据库中
            new_article = article_post_form.save(commit=False)
            # 指定数据库中 id=1 的用户为作者
            # 如果你进行过删除数据表的操作，可能会找不到id=1的用户
            # 此时请重新创建用户，并传入此用户的id
            print(new_article)
            new_article.author = User.objects.get(id=request.user.id)
            # 将新文章保存到数据库中
            new_article.save()
            # 完成后返回到文章列表
            return redirect("article:article_list")
        # 如果数据不合法，返回错误信息
        else:
            return HttpResponse("表单内容有误，请重新填写。")
    # 如果用户请求获取数据
    else:
        # 创建表单类实例
        article_post_form = ArticlePostForm()
        # 赋值上下文
        context = {'article_post_form': article_post_form}
        # 返回模板
        return render(request, 'article/article_create.html', context)


# 更新文章
@login_required(login_url='/userprofile/login/')
def article_update(request, id):
    """
    更新文章的视图函数
    通过POST方法提交表单，更新titile、body字段
    GET方法进入初始表单页面
    id： 文章的 id
    """

    # 获取需要修改的具体文章对象
    article = ArticlePost.objects.get(id=id)
    # 过滤非作者的用户
    if request.user != article.author:
        return HttpResponse("抱歉，你无权修改这篇文章。")

    # 判断用户是否为 POST 提交表单数据
    if request.method == "POST":
        # 将提交的数据赋值到表单实例中
        article_post_form = ArticlePostForm(data=request.POST)
        # 判断提交的数据是否满足模型的要求
        if article_post_form.is_valid():
            # 保存新写入的 title、body 数据并保存
            article.title = request.POST['title']
            article.body = request.POST['body']
            article.save()
            # 完成后返回到修改后的文章中。需传入文章的 id 值
            return redirect("article:article_detail", id=id)
        # 如果数据不合法，返回错误信息
        else:
            return HttpResponse("表单内容有误，请重新填写。")

    # 如果用户 GET 请求获取数据
    else:
        # 创建表单类实例
        article_post_form = ArticlePostForm()
        # 赋值上下文，将 article 文章对象也传递进去，以便提取旧的内容
        context = {'article': article, 'article_post_form': article_post_form}
        # 将响应返回到模板中
        return render(request, 'article/article_update.html', context)


@login_required(login_url='/userprofile/login/')
def article_delete(request, id):
    '''
    删文章
    根据ID删除
    '''
    # 根据 id 获取需要删除的文章
    article = ArticlePost.objects.get(id=id)
    # 调用.delete()方法删除文章
    article.delete()
    # 完成删除后返回文章列表
    return redirect("article:article_list")

templates/article/article_create.html
<!-- extends表明此页面继承自 base.html 文件 -->
{% extends "base.html" %} {% load staticfiles %}
<!-- 写入 base.html 中定义的 title -->
{% block title %} 写文章 {% endblock title %}
<!-- 写入 base.html 中定义的 content -->
{% block content %}
<!-- 写文章表单 -->
<div class="container">
    <div class="row">
        <div class="col-12">
            <br>
            <!-- 提交文章的表单 -->
            <form method="post" action=".">
                <!-- Django中需要POST数据的地方都必须有csrf_token -->
                {% csrf_token %}
                <!-- 文章标题 -->
                <div class="form-group">
                    <!-- 标签 -->
                    <label for="title">文章标题</label>
                    <!-- 文本框 -->
                    <input type="text" class="form-control" id="title" name="title">
                </div>
                <!-- 文章正文 -->
                <div class="form-group">
                    <label for="body">文章正文</label>
                    <!-- 文本区域 -->
                    <textarea type="text" class="form-control" id="body" name="body" rows="12"></textarea>
                </div>
                <!-- 提交按钮 -->
                <button type="submit" class="btn btn-primary">完成</button>
            </form>
        </div>
    </div>
</div>
{% endblock content %}

templates/article/article_detail.html
<!-- extends表明此页面继承自 base.html 文件 -->
{% extends "base.html" %}
{% load staticfiles %}

<!-- 写入 base.html 中定义的 title -->
{% block title %}
文章详情
{% endblock title %}

<!-- 写入 base.html 中定义的 content -->
{% block content %}

<!-- 文章详情 -->
<div class="container">
    <div class="row">
        <div class="col-9">
            <!-- 标题及作者 -->
            <h1 class="col-12 mt-4 mb-4">{{ article.title }}</h1>
            <div class="col-12 alert alert-success">
                <!-- <footer class="blockquote-footer">作者<cite title="Source Title">{{ article.author }}</cite></footer> -->
                作者：{{ article.author }}
                {% if user == article.author %}
                . <a href="#" onclick="confirm_delete()">删除文章</a>
                . <a href="{% url "article:article_update" article.id %}">修改文章</a>
                {% endif %}
                浏览：{{ article.views_counts }}
            </div>

            <!-- 文章正文 -->
            <div class="col-12">
                <!-- 模板语言 输出支持markdown -->
                <p>{{ article.body|safe }}</p>
            </div>
        </div>
        <div class="col-3 mt-4">
            <h4><strong>目录</strong></h4>
            <hr>
            <div>
                {{ toc|safe }}
            </div>
        </div>
    </div>



</div>
<script>
    // 删除文章的函数
    function confirm_delete() {
        // 调用layer弹窗组件
        layer.open({
            // 弹窗标题
            title: "确认删除",
            // 正文
            content: "确认删除这篇文章吗？",
            // 点击确定按钮后调用的回调函数
            yes: function (index, layero) {
                // 指定应当前往的 url
                location.href = '{% url "article:article_delete" article.id %}'
            },
        })
    }
</script>
{% endblock content %}

templates/article/article_list.html
<!-- extends表明此页面继承自 base.html 文件 -->
{% extends "base.html" %}
{% load staticfiles %}

<!-- 写入 base.html 中定义的 title -->
{% block title %}
首页
{% endblock title %}

<!-- 写入 base.html 中定义的 content -->
{% block content %}

<!-- 定义放置文章标题的div容器 -->
<div class="container">
    <nav aria-label="breadcrumb">
        <ol class="breadcrumb">
            <li class="breadcrumb-item">
                <a href="{% url 'article:article_list' %}?search={{ search }}">
                    最新
                </a>
            </li>
            <li class="breadcrumb-item">
                <a href="{% url 'article:article_list' %}?order=views_counts&search={{ search }}">
                    最热
                </a>
            </li>
        </ol>
    </nav>

    <!-- 新增，搜索栏 -->
    <div class="row">
        <div class="col-auto mr-auto">
            <form class="form-inline">
                <label class="sr-only">content</label>
                <input type="text" class="form-control mb-2 mr-sm-2" name="search" placeholder="搜索文章..." required>
            </form>
        </div>
    </div>
    <!-- 新增，搜索提示语 -->
    {% if search %}
        {% if articles %}
        <h4><span style="color: red">"{{ search }}"</span>的搜索结果如下：</h4>
        <hr>
        {% else %}
        <h4>暂无<span style="color: red">"{{ search }}"</span>有关的文章。</h4>
        <hr>
        {% endif %}
    {% endif %}

    <!-- 列表循环 -->
    <div class="row mt-2">
        {% for article in articles %}
        <!-- 文章内容 -->
        <div class="col-12">
            <!-- 栏目 -->
            {% if article.column %}
            <button type="button" class="btn btn-sm mb-2
                            {% if article.column.title == 'Django' %}
                                btn-success
                            {% elif article.column.title == 'Java' %}
                                btn-danger
                            {% elif article.column.title == 'HTML' %}
                                btn-warning
                            {% endif %}
                        ">
                {{ article.column }}
            </button>
            {% endif %}
            <!-- 标题 -->
            <h4>
                <b>
                    <a href="{% url 'article:article_detail' article.id %}" style="color: black;">
                        {{ article.title }}
                    </a>
                </b>
            </h4>
            <!-- 摘要 -->
            <div>
                <p style="color: gray;">
                    {{ article.body|slice:'100' }}...
                </p>
            </div>
            <!-- 注脚 -->
            <p>
                <!-- 附加信息 -->
                <span style="color: green;">
                    {{ article.views_counts }} 浏览&nbsp;&nbsp;&nbsp;
                </span>
                <span style="color: blue;">
                    {{ article.created|date:'Y-m-d' }} 发布&nbsp;&nbsp;&nbsp;
                </span>
                <span style="color: darkred;">
                    {{ article.updated|date:'Y-m-d' }} 更新
                </span>
            </p>
            <hr>
        </div>
        {% endfor %}
    </div>
    <!-- 页码导航 -->
    <div class="pagination row">
        <div class="m-auto">
            <span class="step-links">
                <!-- 如果不是第一页，则显示上翻按钮 -->
                {% if articles.has_previous %}
                <a href="?page=1" class="btn btn-success">
                    &laquo; 1
                </a>
                <span>...</span>
                <a href="?page={{ articles.previous_page_number }}" class="btn btn-secondary">
                    {{ articles.previous_page_number }}
                </a>
                {% endif %}

                <!-- 当前页面 -->
                <span class="current btn btn-danger btn-lg">
                    {{ articles.number }}
                </span>

                <!-- 如果不是最末页，则显示下翻按钮 -->
                {% if articles.has_next %}
                <a href="?page={{ articles.next_page_number }}" class="btn btn-secondary">
                    {{ articles.next_page_number }}
                </a>
                <span>...</span>
                <a href="?page={{ articles.paginator.num_pages }}" class="btn btn-success">
                    {{ articles.paginator.num_pages }} &raquo;
                </a>
                {% endif %}
            </span>
        </div>
    </div>
</div>
{% endblock content %}

templates/article/article_update.html
{% extends "base.html" %} {% load staticfiles %}
{% block title %} 更新文章 {% endblock title %}
{% block content %}
<div class="container">
    <div class="row">
        <div class="col-12">
            <br>
            <form method="post" action=".">
                {% csrf_token %}
                <div class="form-group">
                    <label for="title">文章标题</label>
                    <!-- 在 value 属性中指定文本框的初始值为旧的内容，即 article 对象中的 title 字段 -->
                    <input type="text" class="form-control" id="title" name="title" value="{{ article.title }}">
                </div>
                <div class="form-group">
                    <label for="body">文章正文</label>
                    <!-- 文本域不需要 value 属性，直接在标签体中嵌入数据即可 -->
                    <textarea type="text" class="form-control" id="body" name="body"
                        rows="12">{{ article.body }}</textarea>
                </div>
                <button type="submit" class="btn btn-primary">完成</button>
            </form>
        </div>
    </div>
</div>
{% endblock content %}